#ifndef ERRORS_H
#define ERRORS_H

typedef enum
{
	ERR_INVALID_INPUT,
	ERR_CAR_NOT_FOUND,
	ERR_STATION_NOT_FOUND,
	ERR_MEMORY_ALLOCATION,
	ERR_NO_AVAILABLE_PORT,
	ERR_DUPLICATE_STATION_ID,
	ERR_NULL_POINTER,
	ERR_OPENING_FILE,
	ERR_INVALID_PORT_TYPE,
	ERR_INPUT_NOT_NUM,
	ERR_INVALID_INPUT_FORMAT,
	ERR_PORTLIST_EMPTY,
	ERR_CAR_QUEUE_NULL,
	ERR_CAR_QUEUE_EMPTY,
	ERR_STATION_NULL,
	ERR_INVALID_SEARCH_TYPE,
	ERR_INVALID_BUFFER_SIZE,
	ERR_INVALID_LICENSE_LENGTH,
	ERR_STATION_BST_EMPTY,
	ERR_CAR_BST_EMPTY,
	ERR_UNKNOWN
} ErrorCode;

/**
* Print an error according to the given code.
* @param code: Error code of type enum ErrorCode.
*/
void displayError(ErrorCode code);

#endif

